name: Coverage

on:
  push:
  pull_request:
    types: [opened]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Generate report
        run: go test -v -covermode=count -coverprofile=coverage.out ./...

      - name: Convert to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.5

      - name: Coverage report
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "coverage.lcov"
          min_coverage: 0