name: Coverage

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download gcov2lcov
        run: go get -u github.com/jandelgado/gcov2lcov

      - name: Generate report and convert to lcov
        run: go test -coverprofile=coverage.out -v ./... && gcov2lcov -infile=coverage.out -outfile=lcov.info

      - name: Coverage report
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "lcov.info"
          min_coverage: 50